head1 :
    num_layers: 3
    in_c : 1024
    out_c : 6
    dropout_rate : 0.4
    bn : False
    
head2 :
    num_layers: 3
    in_c : 1024
    out_c : 18
    dropout_rate : 0.4
    bn : False
    
head3 :
    num_layers: 3
    in_c : 1024
    out_c : 128
    dropout_rate : 0.4
    bn : False