head1 :
    num_layers: 2
    in_c : 384 #1024
    out_c : 6
    dropout_rate : 0.4
    bn : False
    
head2 :
    num_layers: 2
    in_c : 384 #1024
    out_c : 18
    dropout_rate : 0.4
    bn : False
    
head3 :
    num_layers: 2
    in_c : 384 #1024
    out_c : 128
    dropout_rate : 0.4
    bn : False